use travelservice;

-- SELECT
SELECT * FROM USER;
SELECT * FROM ROLE;
SELECT * FROM AREA;
SELECT * FROM TICKET;
SELECT * FROM CATEGORY;
SELECT * FROM SERVICE;
SELECT * FROM FAVORITE;
SELECT * FROM SCHEDULE;
SELECT * FROM LINKDATA;
SELECT * FROM REVIEW;
SELECT * FROM ORDERS;
SELECT * FROM ORDERITEM;
SELECT * FROM ORDERITEMBYTICKET;
SELECT * FROM CART;
SELECT * FROM CARTITEM;
SELECT * FROM CARTITEMBYTICKET;

-- INSERT
INSERT INTO ROLE (ROLE) VALUES ('ADMIN');
INSERT INTO ROLE (ROLE) VALUES ('USER');

INSERT INTO AREA (NAME, DATA_URL) VALUES ('Da Nang', '');
INSERT INTO AREA (NAME, DATA_URL) VALUES ('Ho Chi Minh', '');
INSERT INTO AREA (NAME, DATA_URL) VALUES ('Kien Giang', '');
INSERT INTO AREA (NAME, DATA_URL) VALUES ('Nha Trang', '');
INSERT INTO AREA (NAME, DATA_URL) VALUES ('Vung Tau', '');


INSERT INTO CATEGORY (NAME, ICON) VALUES ('Attractions & Tickets', '');
INSERT INTO CATEGORY (NAME, ICON) VALUES ('Travel Services', '');
INSERT INTO CATEGORY (NAME, ICON) VALUES ('Accommodation', '');
INSERT INTO CATEGORY (NAME, ICON) VALUES ('Tours & Sightseeing', '');
INSERT INTO CATEGORY (NAME, ICON) VALUES ('Food & Dining', '');
